apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBb5V8kIUKTwpVCMZSosjy8qJDN1bT4pGpdmLhnEnZZXt2lb4J2x5YEncMkq46p23hJkMSyEsUZWbIxif7dNXiCQOS3CqowYCelZOBfijqnCOXiCBGY6G3qqBb72KcnHcZvMEvtTG0zojYxdv3Uxeb6OmhUHdMB3F9lUlvXr2HB5L3EJZciRSehy60AkLGvHzWdQsqT8VhrHqL7vdyp2ZAQ5OEFz5Usub1Kz1OulNPxwzn3bGXbWRz3JOgsmEnBWXBtsvVpDqI/jaZhaK2/OSAuPRn5ReEq9HBohKteUJ8+gGN5DQhYRY3PWo4V1FVHbFFX2DWAG/TBopasybwr5TzxvnmWrF6qzo5ROsJZyIQm3xoh2bhzAIC6fE93foMbSTe+Hu8Fa9CYMbnMcMLOeb/onv0maZ9Dl1B979PZSYCtwKLnAbYVJwIWrAm8OaAvLydFnOdEI7rIdOB9PiYm0mOSWxj8Gix5EI13mG74Rblr4Z9s+QSx60VVm3Qo8wXquwTKGgYlj0wAA82vuzlCGMTZNIkdjPe7fZBvsX8SP3T5zZSQUmbsSubvKOlmZftrdBMGPQXeX0ZmjUkpVIg5xDT1TD3iTA/yXLXwZjICMULcuBuRkfoQmuIsf2vyL5Srsdp0xt+IKDY3S1pRxUKQAEXl99rYVv9OqJiLGY0zBzRMRHim7L511Q1GhbMEbNYljxBc1axery4ccO6badRtA5lk
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
