name: "CI workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - test

jobs:
  build: 
      name: "environment setup"
      runs-on: ubuntu-latest
      steps:
        - name: using secrets
          run: echo "Secrets are ${{ secrets.API_KEY }}"

        - name: using variables
          run: echo "variables are ${{ env.NAME }}"
  test:
      name: "testing the python application"
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout repository"
          uses: actions/checkout@v4
          
        - name: "Setup environment"
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: "install the dependencies"
          run: |
            pip install -r requirements.txt

        - name: "test"
          run: pytest
